// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cc/toprank/byd/reception/protos/MiniDeviceInfo.proto

package com.github.ibole.microservice.common;

public final class MiniDeviceInfoProto {
  private MiniDeviceInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MiniDeviceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MiniDeviceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *手机型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    java.lang.String getModel();
    /**
     * <pre>
     *手机型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <pre>
     *OS版本信息
     * </pre>
     *
     * <code>string osVersion = 2;</code>
     */
    java.lang.String getOsVersion();
    /**
     * <pre>
     *OS版本信息
     * </pre>
     *
     * <code>string osVersion = 2;</code>
     */
    com.google.protobuf.ByteString
        getOsVersionBytes();

    /**
     * <pre>
     *当前APP的版本号
     * </pre>
     *
     * <code>string versionCode = 3;</code>
     */
    java.lang.String getVersionCode();
    /**
     * <pre>
     *当前APP的版本号
     * </pre>
     *
     * <code>string versionCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionCodeBytes();

    /**
     * <pre>
     *本机串号imei
     * </pre>
     *
     * <code>string imei = 4;</code>
     */
    java.lang.String getImei();
    /**
     * <pre>
     *本机串号imei
     * </pre>
     *
     * <code>string imei = 4;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <pre>
     *IP address
     * </pre>
     *
     * <code>string ipAddress = 5;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <pre>
     *IP address
     * </pre>
     *
     * <code>string ipAddress = 5;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();
  }
  /**
   * <pre>
   * The request message containing the device model/osVersion/versionCode/imei/ip address.
   * </pre>
   *
   * Protobuf type {@code MiniDeviceInfo}
   */
  public  static final class MiniDeviceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MiniDeviceInfo)
      MiniDeviceInfoOrBuilder {
    // Use MiniDeviceInfo.newBuilder() to construct.
    private MiniDeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MiniDeviceInfo() {
      model_ = "";
      osVersion_ = "";
      versionCode_ = "";
      imei_ = "";
      ipAddress_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MiniDeviceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              osVersion_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              versionCode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              imei_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              ipAddress_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ibole.microservice.common.MiniDeviceInfoProto.internal_static_MiniDeviceInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ibole.microservice.common.MiniDeviceInfoProto.internal_static_MiniDeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.class, com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.Builder.class);
    }

    public static final int MODEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object model_;
    /**
     * <pre>
     *手机型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSVERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object osVersion_;
    /**
     * <pre>
     *OS版本信息
     * </pre>
     *
     * <code>string osVersion = 2;</code>
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *OS版本信息
     * </pre>
     *
     * <code>string osVersion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSIONCODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object versionCode_;
    /**
     * <pre>
     *当前APP的版本号
     * </pre>
     *
     * <code>string versionCode = 3;</code>
     */
    public java.lang.String getVersionCode() {
      java.lang.Object ref = versionCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        versionCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前APP的版本号
     * </pre>
     *
     * <code>string versionCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionCodeBytes() {
      java.lang.Object ref = versionCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMEI_FIELD_NUMBER = 4;
    private volatile java.lang.Object imei_;
    /**
     * <pre>
     *本机串号imei
     * </pre>
     *
     * <code>string imei = 4;</code>
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imei_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *本机串号imei
     * </pre>
     *
     * <code>string imei = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object ipAddress_;
    /**
     * <pre>
     *IP address
     * </pre>
     *
     * <code>string ipAddress = 5;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *IP address
     * </pre>
     *
     * <code>string ipAddress = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, model_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, osVersion_);
      }
      if (!getVersionCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, versionCode_);
      }
      if (!getImeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imei_);
      }
      if (!getIpAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ipAddress_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, model_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, osVersion_);
      }
      if (!getVersionCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, versionCode_);
      }
      if (!getImeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imei_);
      }
      if (!getIpAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ipAddress_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo)) {
        return super.equals(obj);
      }
      com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo other = (com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo) obj;

      boolean result = true;
      result = result && getModel()
          .equals(other.getModel());
      result = result && getOsVersion()
          .equals(other.getOsVersion());
      result = result && getVersionCode()
          .equals(other.getVersionCode());
      result = result && getImei()
          .equals(other.getImei());
      result = result && getIpAddress()
          .equals(other.getIpAddress());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + OSVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getOsVersion().hashCode();
      hash = (37 * hash) + VERSIONCODE_FIELD_NUMBER;
      hash = (53 * hash) + getVersionCode().hashCode();
      hash = (37 * hash) + IMEI_FIELD_NUMBER;
      hash = (53 * hash) + getImei().hashCode();
      hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the device model/osVersion/versionCode/imei/ip address.
     * </pre>
     *
     * Protobuf type {@code MiniDeviceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MiniDeviceInfo)
        com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.ibole.microservice.common.MiniDeviceInfoProto.internal_static_MiniDeviceInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.ibole.microservice.common.MiniDeviceInfoProto.internal_static_MiniDeviceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.class, com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.Builder.class);
      }

      // Construct using com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        model_ = "";

        osVersion_ = "";

        versionCode_ = "";

        imei_ = "";

        ipAddress_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.ibole.microservice.common.MiniDeviceInfoProto.internal_static_MiniDeviceInfo_descriptor;
      }

      public com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo getDefaultInstanceForType() {
        return com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.getDefaultInstance();
      }

      public com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo build() {
        com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo buildPartial() {
        com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo result = new com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo(this);
        result.model_ = model_;
        result.osVersion_ = osVersion_;
        result.versionCode_ = versionCode_;
        result.imei_ = imei_;
        result.ipAddress_ = ipAddress_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo) {
          return mergeFrom((com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo other) {
        if (other == com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo.getDefaultInstance()) return this;
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (!other.getOsVersion().isEmpty()) {
          osVersion_ = other.osVersion_;
          onChanged();
        }
        if (!other.getVersionCode().isEmpty()) {
          versionCode_ = other.versionCode_;
          onChanged();
        }
        if (!other.getImei().isEmpty()) {
          imei_ = other.imei_;
          onChanged();
        }
        if (!other.getIpAddress().isEmpty()) {
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <pre>
       *手机型号
       * </pre>
       *
       * <code>string model = 1;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机型号
       * </pre>
       *
       * <code>string model = 1;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机型号
       * </pre>
       *
       * <code>string model = 1;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机型号
       * </pre>
       *
       * <code>string model = 1;</code>
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机型号
       * </pre>
       *
       * <code>string model = 1;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object osVersion_ = "";
      /**
       * <pre>
       *OS版本信息
       * </pre>
       *
       * <code>string osVersion = 2;</code>
       */
      public java.lang.String getOsVersion() {
        java.lang.Object ref = osVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          osVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *OS版本信息
       * </pre>
       *
       * <code>string osVersion = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOsVersionBytes() {
        java.lang.Object ref = osVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          osVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *OS版本信息
       * </pre>
       *
       * <code>string osVersion = 2;</code>
       */
      public Builder setOsVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *OS版本信息
       * </pre>
       *
       * <code>string osVersion = 2;</code>
       */
      public Builder clearOsVersion() {
        
        osVersion_ = getDefaultInstance().getOsVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *OS版本信息
       * </pre>
       *
       * <code>string osVersion = 2;</code>
       */
      public Builder setOsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object versionCode_ = "";
      /**
       * <pre>
       *当前APP的版本号
       * </pre>
       *
       * <code>string versionCode = 3;</code>
       */
      public java.lang.String getVersionCode() {
        java.lang.Object ref = versionCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          versionCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当前APP的版本号
       * </pre>
       *
       * <code>string versionCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionCodeBytes() {
        java.lang.Object ref = versionCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前APP的版本号
       * </pre>
       *
       * <code>string versionCode = 3;</code>
       */
      public Builder setVersionCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        versionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前APP的版本号
       * </pre>
       *
       * <code>string versionCode = 3;</code>
       */
      public Builder clearVersionCode() {
        
        versionCode_ = getDefaultInstance().getVersionCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前APP的版本号
       * </pre>
       *
       * <code>string versionCode = 3;</code>
       */
      public Builder setVersionCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        versionCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imei_ = "";
      /**
       * <pre>
       *本机串号imei
       * </pre>
       *
       * <code>string imei = 4;</code>
       */
      public java.lang.String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *本机串号imei
       * </pre>
       *
       * <code>string imei = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        java.lang.Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *本机串号imei
       * </pre>
       *
       * <code>string imei = 4;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *本机串号imei
       * </pre>
       *
       * <code>string imei = 4;</code>
       */
      public Builder clearImei() {
        
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *本机串号imei
       * </pre>
       *
       * <code>string imei = 4;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imei_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ipAddress_ = "";
      /**
       * <pre>
       *IP address
       * </pre>
       *
       * <code>string ipAddress = 5;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *IP address
       * </pre>
       *
       * <code>string ipAddress = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *IP address
       * </pre>
       *
       * <code>string ipAddress = 5;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *IP address
       * </pre>
       *
       * <code>string ipAddress = 5;</code>
       */
      public Builder clearIpAddress() {
        
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *IP address
       * </pre>
       *
       * <code>string ipAddress = 5;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipAddress_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MiniDeviceInfo)
    }

    // @@protoc_insertion_point(class_scope:MiniDeviceInfo)
    private static final com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo();
    }

    public static com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MiniDeviceInfo>
        PARSER = new com.google.protobuf.AbstractParser<MiniDeviceInfo>() {
      public MiniDeviceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MiniDeviceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MiniDeviceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MiniDeviceInfo> getParserForType() {
      return PARSER;
    }

    public com.github.ibole.microservice.common.MiniDeviceInfoProto.MiniDeviceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MiniDeviceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MiniDeviceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4cc/toprank/byd/reception/protos/MiniDe" +
      "viceInfo.proto\"h\n\016MiniDeviceInfo\022\r\n\005mode" +
      "l\030\001 \001(\t\022\021\n\tosVersion\030\002 \001(\t\022\023\n\013versionCod" +
      "e\030\003 \001(\t\022\014\n\004imei\030\004 \001(\t\022\021\n\tipAddress\030\005 \001(\t" +
      "BA\n$com.github.ibole.microservice.common" +
      "B\023MiniDeviceInfoProto\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MiniDeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MiniDeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MiniDeviceInfo_descriptor,
        new java.lang.String[] { "Model", "OsVersion", "VersionCode", "Imei", "IpAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
