// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cc/toprank/byd/reception/protos/UserPrincipal.proto

package com.github.ibole.microservice.common;

public final class UserPrincipalProto {
  private UserPrincipalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserPrincipalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserPrincipal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string clientId = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string loginId = 2;</code>
     */
    java.lang.String getLoginId();
    /**
     * <code>string loginId = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginIdBytes();

    /**
     * <code>string userName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>.AuthTokenInfo authToken = 4;</code>
     */
    boolean hasAuthToken();
    /**
     * <code>.AuthTokenInfo authToken = 4;</code>
     */
    com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo getAuthToken();
    /**
     * <code>.AuthTokenInfo authToken = 4;</code>
     */
    com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder getAuthTokenOrBuilder();
  }
  /**
   * <pre>
   * The request message containing the clientId/loginId/AuthTokenInfo
   * </pre>
   *
   * Protobuf type {@code UserPrincipal}
   */
  public  static final class UserPrincipal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserPrincipal)
      UserPrincipalOrBuilder {
    // Use UserPrincipal.newBuilder() to construct.
    private UserPrincipal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserPrincipal() {
      clientId_ = "";
      loginId_ = "";
      userName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserPrincipal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              loginId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 34: {
              com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder subBuilder = null;
              if (authToken_ != null) {
                subBuilder = authToken_.toBuilder();
              }
              authToken_ = input.readMessage(com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(authToken_);
                authToken_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_UserPrincipal_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_UserPrincipal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.class, com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGINID_FIELD_NUMBER = 2;
    private volatile java.lang.Object loginId_;
    /**
     * <code>string loginId = 2;</code>
     */
    public java.lang.String getLoginId() {
      java.lang.Object ref = loginId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginId_ = s;
        return s;
      }
    }
    /**
     * <code>string loginId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginIdBytes() {
      java.lang.Object ref = loginId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHTOKEN_FIELD_NUMBER = 4;
    private com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo authToken_;
    /**
     * <code>.AuthTokenInfo authToken = 4;</code>
     */
    public boolean hasAuthToken() {
      return authToken_ != null;
    }
    /**
     * <code>.AuthTokenInfo authToken = 4;</code>
     */
    public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo getAuthToken() {
      return authToken_ == null ? com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.getDefaultInstance() : authToken_;
    }
    /**
     * <code>.AuthTokenInfo authToken = 4;</code>
     */
    public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder getAuthTokenOrBuilder() {
      return getAuthToken();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getLoginIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (authToken_ != null) {
        output.writeMessage(4, getAuthToken());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getLoginIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (authToken_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAuthToken());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal)) {
        return super.equals(obj);
      }
      com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal other = (com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getLoginId()
          .equals(other.getLoginId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && (hasAuthToken() == other.hasAuthToken());
      if (hasAuthToken()) {
        result = result && getAuthToken()
            .equals(other.getAuthToken());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + LOGINID_FIELD_NUMBER;
      hash = (53 * hash) + getLoginId().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      if (hasAuthToken()) {
        hash = (37 * hash) + AUTHTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAuthToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the clientId/loginId/AuthTokenInfo
     * </pre>
     *
     * Protobuf type {@code UserPrincipal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserPrincipal)
        com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_UserPrincipal_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_UserPrincipal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.class, com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.Builder.class);
      }

      // Construct using com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = "";

        loginId_ = "";

        userName_ = "";

        if (authTokenBuilder_ == null) {
          authToken_ = null;
        } else {
          authToken_ = null;
          authTokenBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_UserPrincipal_descriptor;
      }

      public com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal getDefaultInstanceForType() {
        return com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.getDefaultInstance();
      }

      public com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal build() {
        com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal buildPartial() {
        com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal result = new com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal(this);
        result.clientId_ = clientId_;
        result.loginId_ = loginId_;
        result.userName_ = userName_;
        if (authTokenBuilder_ == null) {
          result.authToken_ = authToken_;
        } else {
          result.authToken_ = authTokenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal) {
          return mergeFrom((com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal other) {
        if (other == com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getLoginId().isEmpty()) {
          loginId_ = other.loginId_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasAuthToken()) {
          mergeAuthToken(other.getAuthToken());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string clientId = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginId_ = "";
      /**
       * <code>string loginId = 2;</code>
       */
      public java.lang.String getLoginId() {
        java.lang.Object ref = loginId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginIdBytes() {
        java.lang.Object ref = loginId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public Builder setLoginId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public Builder clearLoginId() {
        
        loginId_ = getDefaultInstance().getLoginId();
        onChanged();
        return this;
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public Builder setLoginIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 3;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo authToken_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder> authTokenBuilder_;
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public boolean hasAuthToken() {
        return authTokenBuilder_ != null || authToken_ != null;
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo getAuthToken() {
        if (authTokenBuilder_ == null) {
          return authToken_ == null ? com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.getDefaultInstance() : authToken_;
        } else {
          return authTokenBuilder_.getMessage();
        }
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public Builder setAuthToken(com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo value) {
        if (authTokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          authToken_ = value;
          onChanged();
        } else {
          authTokenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public Builder setAuthToken(
          com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder builderForValue) {
        if (authTokenBuilder_ == null) {
          authToken_ = builderForValue.build();
          onChanged();
        } else {
          authTokenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public Builder mergeAuthToken(com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo value) {
        if (authTokenBuilder_ == null) {
          if (authToken_ != null) {
            authToken_ =
              com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.newBuilder(authToken_).mergeFrom(value).buildPartial();
          } else {
            authToken_ = value;
          }
          onChanged();
        } else {
          authTokenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public Builder clearAuthToken() {
        if (authTokenBuilder_ == null) {
          authToken_ = null;
          onChanged();
        } else {
          authToken_ = null;
          authTokenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder getAuthTokenBuilder() {
        
        onChanged();
        return getAuthTokenFieldBuilder().getBuilder();
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder getAuthTokenOrBuilder() {
        if (authTokenBuilder_ != null) {
          return authTokenBuilder_.getMessageOrBuilder();
        } else {
          return authToken_ == null ?
              com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.getDefaultInstance() : authToken_;
        }
      }
      /**
       * <code>.AuthTokenInfo authToken = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder> 
          getAuthTokenFieldBuilder() {
        if (authTokenBuilder_ == null) {
          authTokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder>(
                  getAuthToken(),
                  getParentForChildren(),
                  isClean());
          authToken_ = null;
        }
        return authTokenBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserPrincipal)
    }

    // @@protoc_insertion_point(class_scope:UserPrincipal)
    private static final com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal();
    }

    public static com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserPrincipal>
        PARSER = new com.google.protobuf.AbstractParser<UserPrincipal>() {
      public UserPrincipal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserPrincipal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserPrincipal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserPrincipal> getParserForType() {
      return PARSER;
    }

    public com.github.ibole.microservice.common.UserPrincipalProto.UserPrincipal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthTokenInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthTokenInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *identify whether the token that user provided is authenticated or not,
     * user need to login if loginRequired is true.
     * </pre>
     *
     * <code>bool loginRequired = 1;</code>
     */
    boolean getLoginRequired();

    /**
     * <pre>
     *if the access token has renewed
     * </pre>
     *
     * <code>bool renewAccessToken = 2;</code>
     */
    boolean getRenewAccessToken();

    /**
     * <code>string refreshToken = 3;</code>
     */
    java.lang.String getRefreshToken();
    /**
     * <code>string refreshToken = 3;</code>
     */
    com.google.protobuf.ByteString
        getRefreshTokenBytes();

    /**
     * <code>string accessToken = 4;</code>
     */
    java.lang.String getAccessToken();
    /**
     * <code>string accessToken = 4;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();
  }
  /**
   * <pre>
   * The request message containing the loginRequired/renewAccessToken/refresh token/access token
   * </pre>
   *
   * Protobuf type {@code AuthTokenInfo}
   */
  public  static final class AuthTokenInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuthTokenInfo)
      AuthTokenInfoOrBuilder {
    // Use AuthTokenInfo.newBuilder() to construct.
    private AuthTokenInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthTokenInfo() {
      loginRequired_ = false;
      renewAccessToken_ = false;
      refreshToken_ = "";
      accessToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AuthTokenInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              loginRequired_ = input.readBool();
              break;
            }
            case 16: {

              renewAccessToken_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              refreshToken_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_AuthTokenInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_AuthTokenInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.class, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder.class);
    }

    public static final int LOGINREQUIRED_FIELD_NUMBER = 1;
    private boolean loginRequired_;
    /**
     * <pre>
     *identify whether the token that user provided is authenticated or not,
     * user need to login if loginRequired is true.
     * </pre>
     *
     * <code>bool loginRequired = 1;</code>
     */
    public boolean getLoginRequired() {
      return loginRequired_;
    }

    public static final int RENEWACCESSTOKEN_FIELD_NUMBER = 2;
    private boolean renewAccessToken_;
    /**
     * <pre>
     *if the access token has renewed
     * </pre>
     *
     * <code>bool renewAccessToken = 2;</code>
     */
    public boolean getRenewAccessToken() {
      return renewAccessToken_;
    }

    public static final int REFRESHTOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object refreshToken_;
    /**
     * <code>string refreshToken = 3;</code>
     */
    public java.lang.String getRefreshToken() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refreshToken_ = s;
        return s;
      }
    }
    /**
     * <code>string refreshToken = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refreshToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string accessToken = 4;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string accessToken = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (loginRequired_ != false) {
        output.writeBool(1, loginRequired_);
      }
      if (renewAccessToken_ != false) {
        output.writeBool(2, renewAccessToken_);
      }
      if (!getRefreshTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, refreshToken_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessToken_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (loginRequired_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, loginRequired_);
      }
      if (renewAccessToken_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, renewAccessToken_);
      }
      if (!getRefreshTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, refreshToken_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessToken_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo)) {
        return super.equals(obj);
      }
      com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo other = (com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo) obj;

      boolean result = true;
      result = result && (getLoginRequired()
          == other.getLoginRequired());
      result = result && (getRenewAccessToken()
          == other.getRenewAccessToken());
      result = result && getRefreshToken()
          .equals(other.getRefreshToken());
      result = result && getAccessToken()
          .equals(other.getAccessToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGINREQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLoginRequired());
      hash = (37 * hash) + RENEWACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRenewAccessToken());
      hash = (37 * hash) + REFRESHTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRefreshToken().hashCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the loginRequired/renewAccessToken/refresh token/access token
     * </pre>
     *
     * Protobuf type {@code AuthTokenInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthTokenInfo)
        com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_AuthTokenInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_AuthTokenInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.class, com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.Builder.class);
      }

      // Construct using com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        loginRequired_ = false;

        renewAccessToken_ = false;

        refreshToken_ = "";

        accessToken_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.ibole.microservice.common.UserPrincipalProto.internal_static_AuthTokenInfo_descriptor;
      }

      public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo getDefaultInstanceForType() {
        return com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.getDefaultInstance();
      }

      public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo build() {
        com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo buildPartial() {
        com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo result = new com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo(this);
        result.loginRequired_ = loginRequired_;
        result.renewAccessToken_ = renewAccessToken_;
        result.refreshToken_ = refreshToken_;
        result.accessToken_ = accessToken_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo) {
          return mergeFrom((com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo other) {
        if (other == com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo.getDefaultInstance()) return this;
        if (other.getLoginRequired() != false) {
          setLoginRequired(other.getLoginRequired());
        }
        if (other.getRenewAccessToken() != false) {
          setRenewAccessToken(other.getRenewAccessToken());
        }
        if (!other.getRefreshToken().isEmpty()) {
          refreshToken_ = other.refreshToken_;
          onChanged();
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean loginRequired_ ;
      /**
       * <pre>
       *identify whether the token that user provided is authenticated or not,
       * user need to login if loginRequired is true.
       * </pre>
       *
       * <code>bool loginRequired = 1;</code>
       */
      public boolean getLoginRequired() {
        return loginRequired_;
      }
      /**
       * <pre>
       *identify whether the token that user provided is authenticated or not,
       * user need to login if loginRequired is true.
       * </pre>
       *
       * <code>bool loginRequired = 1;</code>
       */
      public Builder setLoginRequired(boolean value) {
        
        loginRequired_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *identify whether the token that user provided is authenticated or not,
       * user need to login if loginRequired is true.
       * </pre>
       *
       * <code>bool loginRequired = 1;</code>
       */
      public Builder clearLoginRequired() {
        
        loginRequired_ = false;
        onChanged();
        return this;
      }

      private boolean renewAccessToken_ ;
      /**
       * <pre>
       *if the access token has renewed
       * </pre>
       *
       * <code>bool renewAccessToken = 2;</code>
       */
      public boolean getRenewAccessToken() {
        return renewAccessToken_;
      }
      /**
       * <pre>
       *if the access token has renewed
       * </pre>
       *
       * <code>bool renewAccessToken = 2;</code>
       */
      public Builder setRenewAccessToken(boolean value) {
        
        renewAccessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *if the access token has renewed
       * </pre>
       *
       * <code>bool renewAccessToken = 2;</code>
       */
      public Builder clearRenewAccessToken() {
        
        renewAccessToken_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object refreshToken_ = "";
      /**
       * <code>string refreshToken = 3;</code>
       */
      public java.lang.String getRefreshToken() {
        java.lang.Object ref = refreshToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refreshToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRefreshTokenBytes() {
        java.lang.Object ref = refreshToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refreshToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public Builder setRefreshToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refreshToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public Builder clearRefreshToken() {
        
        refreshToken_ = getDefaultInstance().getRefreshToken();
        onChanged();
        return this;
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public Builder setRefreshTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refreshToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string accessToken = 4;</code>
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accessToken = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessToken = 4;</code>
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 4;</code>
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 4;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AuthTokenInfo)
    }

    // @@protoc_insertion_point(class_scope:AuthTokenInfo)
    private static final com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo();
    }

    public static com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthTokenInfo>
        PARSER = new com.google.protobuf.AbstractParser<AuthTokenInfo>() {
      public AuthTokenInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AuthTokenInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthTokenInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthTokenInfo> getParserForType() {
      return PARSER;
    }

    public com.github.ibole.microservice.common.UserPrincipalProto.AuthTokenInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserPrincipal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserPrincipal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthTokenInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthTokenInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3cc/toprank/byd/reception/protos/UserPr" +
      "incipal.proto\"g\n\rUserPrincipal\022\020\n\010client" +
      "Id\030\001 \001(\t\022\017\n\007loginId\030\002 \001(\t\022\020\n\010userName\030\003 " +
      "\001(\t\022!\n\tauthToken\030\004 \001(\0132\016.AuthTokenInfo\"k" +
      "\n\rAuthTokenInfo\022\025\n\rloginRequired\030\001 \001(\010\022\030" +
      "\n\020renewAccessToken\030\002 \001(\010\022\024\n\014refreshToken" +
      "\030\003 \001(\t\022\023\n\013accessToken\030\004 \001(\tB@\n$com.githu" +
      "b.ibole.microservice.commonB\022UserPrincip" +
      "alProto\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserPrincipal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserPrincipal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserPrincipal_descriptor,
        new java.lang.String[] { "ClientId", "LoginId", "UserName", "AuthToken", });
    internal_static_AuthTokenInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AuthTokenInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthTokenInfo_descriptor,
        new java.lang.String[] { "LoginRequired", "RenewAccessToken", "RefreshToken", "AccessToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
