// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cc/toprank/byd/reception/protos/ErrorDetails.proto

package com.github.ibole.microservice.common.exception;

public final class ErrorDetailsProto {
  private ErrorDetailsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string generalCode = 1;</code>
     */
    java.lang.String getGeneralCode();
    /**
     * <code>string generalCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getGeneralCodeBytes();

    /**
     * <code>string specificCode = 2;</code>
     */
    java.lang.String getSpecificCode();
    /**
     * <code>string specificCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getSpecificCodeBytes();

    /**
     * <code>string specificMessage = 3;</code>
     */
    java.lang.String getSpecificMessage();
    /**
     * <code>string specificMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getSpecificMessageBytes();

    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    java.util.List<java.lang.String>
        getDetailedMessageList();
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    int getDetailedMessageCount();
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    java.lang.String getDetailedMessage(int index);
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    com.google.protobuf.ByteString
        getDetailedMessageBytes(int index);
  }
  /**
   * <pre>
   * The request message containing the generalCode/specificCode/specificMessage/details
   * </pre>
   *
   * Protobuf type {@code ErrorDetails}
   */
  public  static final class ErrorDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ErrorDetails)
      ErrorDetailsOrBuilder {
    // Use ErrorDetails.newBuilder() to construct.
    private ErrorDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorDetails() {
      generalCode_ = "";
      specificCode_ = "";
      specificMessage_ = "";
      detailedMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              generalCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              specificCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              specificMessage_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                detailedMessage_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              detailedMessage_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          detailedMessage_ = detailedMessage_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ibole.microservice.common.exception.ErrorDetailsProto.internal_static_ErrorDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ibole.microservice.common.exception.ErrorDetailsProto.internal_static_ErrorDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.class, com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.Builder.class);
    }

    private int bitField0_;
    public static final int GENERALCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object generalCode_;
    /**
     * <code>string generalCode = 1;</code>
     */
    public java.lang.String getGeneralCode() {
      java.lang.Object ref = generalCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        generalCode_ = s;
        return s;
      }
    }
    /**
     * <code>string generalCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGeneralCodeBytes() {
      java.lang.Object ref = generalCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        generalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECIFICCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object specificCode_;
    /**
     * <code>string specificCode = 2;</code>
     */
    public java.lang.String getSpecificCode() {
      java.lang.Object ref = specificCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specificCode_ = s;
        return s;
      }
    }
    /**
     * <code>string specificCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSpecificCodeBytes() {
      java.lang.Object ref = specificCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specificCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECIFICMESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object specificMessage_;
    /**
     * <code>string specificMessage = 3;</code>
     */
    public java.lang.String getSpecificMessage() {
      java.lang.Object ref = specificMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specificMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string specificMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSpecificMessageBytes() {
      java.lang.Object ref = specificMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specificMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAILEDMESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList detailedMessage_;
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDetailedMessageList() {
      return detailedMessage_;
    }
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    public int getDetailedMessageCount() {
      return detailedMessage_.size();
    }
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    public java.lang.String getDetailedMessage(int index) {
      return detailedMessage_.get(index);
    }
    /**
     * <code>repeated string detailedMessage = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDetailedMessageBytes(int index) {
      return detailedMessage_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGeneralCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, generalCode_);
      }
      if (!getSpecificCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, specificCode_);
      }
      if (!getSpecificMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, specificMessage_);
      }
      for (int i = 0; i < detailedMessage_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, detailedMessage_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGeneralCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, generalCode_);
      }
      if (!getSpecificCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, specificCode_);
      }
      if (!getSpecificMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, specificMessage_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < detailedMessage_.size(); i++) {
          dataSize += computeStringSizeNoTag(detailedMessage_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDetailedMessageList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails)) {
        return super.equals(obj);
      }
      com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails other = (com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails) obj;

      boolean result = true;
      result = result && getGeneralCode()
          .equals(other.getGeneralCode());
      result = result && getSpecificCode()
          .equals(other.getSpecificCode());
      result = result && getSpecificMessage()
          .equals(other.getSpecificMessage());
      result = result && getDetailedMessageList()
          .equals(other.getDetailedMessageList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GENERALCODE_FIELD_NUMBER;
      hash = (53 * hash) + getGeneralCode().hashCode();
      hash = (37 * hash) + SPECIFICCODE_FIELD_NUMBER;
      hash = (53 * hash) + getSpecificCode().hashCode();
      hash = (37 * hash) + SPECIFICMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getSpecificMessage().hashCode();
      if (getDetailedMessageCount() > 0) {
        hash = (37 * hash) + DETAILEDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getDetailedMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the generalCode/specificCode/specificMessage/details
     * </pre>
     *
     * Protobuf type {@code ErrorDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorDetails)
        com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.ibole.microservice.common.exception.ErrorDetailsProto.internal_static_ErrorDetails_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.ibole.microservice.common.exception.ErrorDetailsProto.internal_static_ErrorDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.class, com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.Builder.class);
      }

      // Construct using com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        generalCode_ = "";

        specificCode_ = "";

        specificMessage_ = "";

        detailedMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.ibole.microservice.common.exception.ErrorDetailsProto.internal_static_ErrorDetails_descriptor;
      }

      public com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails getDefaultInstanceForType() {
        return com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.getDefaultInstance();
      }

      public com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails build() {
        com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails buildPartial() {
        com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails result = new com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.generalCode_ = generalCode_;
        result.specificCode_ = specificCode_;
        result.specificMessage_ = specificMessage_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          detailedMessage_ = detailedMessage_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.detailedMessage_ = detailedMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails) {
          return mergeFrom((com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails other) {
        if (other == com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails.getDefaultInstance()) return this;
        if (!other.getGeneralCode().isEmpty()) {
          generalCode_ = other.generalCode_;
          onChanged();
        }
        if (!other.getSpecificCode().isEmpty()) {
          specificCode_ = other.specificCode_;
          onChanged();
        }
        if (!other.getSpecificMessage().isEmpty()) {
          specificMessage_ = other.specificMessage_;
          onChanged();
        }
        if (!other.detailedMessage_.isEmpty()) {
          if (detailedMessage_.isEmpty()) {
            detailedMessage_ = other.detailedMessage_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDetailedMessageIsMutable();
            detailedMessage_.addAll(other.detailedMessage_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object generalCode_ = "";
      /**
       * <code>string generalCode = 1;</code>
       */
      public java.lang.String getGeneralCode() {
        java.lang.Object ref = generalCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          generalCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string generalCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGeneralCodeBytes() {
        java.lang.Object ref = generalCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          generalCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string generalCode = 1;</code>
       */
      public Builder setGeneralCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        generalCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string generalCode = 1;</code>
       */
      public Builder clearGeneralCode() {
        
        generalCode_ = getDefaultInstance().getGeneralCode();
        onChanged();
        return this;
      }
      /**
       * <code>string generalCode = 1;</code>
       */
      public Builder setGeneralCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        generalCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object specificCode_ = "";
      /**
       * <code>string specificCode = 2;</code>
       */
      public java.lang.String getSpecificCode() {
        java.lang.Object ref = specificCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          specificCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string specificCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSpecificCodeBytes() {
        java.lang.Object ref = specificCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          specificCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string specificCode = 2;</code>
       */
      public Builder setSpecificCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        specificCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string specificCode = 2;</code>
       */
      public Builder clearSpecificCode() {
        
        specificCode_ = getDefaultInstance().getSpecificCode();
        onChanged();
        return this;
      }
      /**
       * <code>string specificCode = 2;</code>
       */
      public Builder setSpecificCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        specificCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object specificMessage_ = "";
      /**
       * <code>string specificMessage = 3;</code>
       */
      public java.lang.String getSpecificMessage() {
        java.lang.Object ref = specificMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          specificMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string specificMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSpecificMessageBytes() {
        java.lang.Object ref = specificMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          specificMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string specificMessage = 3;</code>
       */
      public Builder setSpecificMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        specificMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string specificMessage = 3;</code>
       */
      public Builder clearSpecificMessage() {
        
        specificMessage_ = getDefaultInstance().getSpecificMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string specificMessage = 3;</code>
       */
      public Builder setSpecificMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        specificMessage_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList detailedMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDetailedMessageIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          detailedMessage_ = new com.google.protobuf.LazyStringArrayList(detailedMessage_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDetailedMessageList() {
        return detailedMessage_.getUnmodifiableView();
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public int getDetailedMessageCount() {
        return detailedMessage_.size();
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public java.lang.String getDetailedMessage(int index) {
        return detailedMessage_.get(index);
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDetailedMessageBytes(int index) {
        return detailedMessage_.getByteString(index);
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public Builder setDetailedMessage(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDetailedMessageIsMutable();
        detailedMessage_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public Builder addDetailedMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDetailedMessageIsMutable();
        detailedMessage_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public Builder addAllDetailedMessage(
          java.lang.Iterable<java.lang.String> values) {
        ensureDetailedMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, detailedMessage_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public Builder clearDetailedMessage() {
        detailedMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string detailedMessage = 4;</code>
       */
      public Builder addDetailedMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDetailedMessageIsMutable();
        detailedMessage_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ErrorDetails)
    }

    // @@protoc_insertion_point(class_scope:ErrorDetails)
    private static final com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails();
    }

    public static com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorDetails>
        PARSER = new com.google.protobuf.AbstractParser<ErrorDetails>() {
      public ErrorDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorDetails> getParserForType() {
      return PARSER;
    }

    public com.github.ibole.microservice.common.exception.ErrorDetailsProto.ErrorDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2cc/toprank/byd/reception/protos/ErrorD" +
      "etails.proto\"k\n\014ErrorDetails\022\023\n\013generalC" +
      "ode\030\001 \001(\t\022\024\n\014specificCode\030\002 \001(\t\022\027\n\017speci" +
      "ficMessage\030\003 \001(\t\022\027\n\017detailedMessage\030\004 \003(" +
      "\tBI\n.com.github.ibole.microservice.commo" +
      "n.exceptionB\021ErrorDetailsProto\242\002\003RTGb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ErrorDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErrorDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorDetails_descriptor,
        new java.lang.String[] { "GeneralCode", "SpecificCode", "SpecificMessage", "DetailedMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
